In [3]:
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
import utility

reload(utility)
from utility import *

from scipy.optimize import curve_fit
from SecondaryValue import SecondaryValue

In [9]:
org_compliance = 0.0098
a_an = 26  # cm^2
a_org = 6.4e-2  # cm^2
a_fol = 25  # cm^2
i_ein = 100e-3  # watt/cm^2
u_ref = 32.2e-3  # volt

In [10]:
intensity = SecondaryValue('u/u_ref*i0', defaults=dict(i0=i_ein, u_ref=u_ref))

In [36]:
intensities, d_intensites = intensity(u=([.011, 0.017, .021, .026, .032], 2e-3))

In [37]:
d_intensites

array([0.00621118, 0.00621118, 0.00621118, 0.00621118, 0.00621118])

In [38]:
ccurves = [parse_ccurve(f'../messungen/191114_OM_VB/2_{point}.dat') \
           for point in ['a', 'b', 'c', 'd', 'e']]

ccurve_specs = [(intsy, analyze_ccurve(curve, a_an, intsy)) \
                for curve, intsy in zip(ccurves, intensities)]

In [24]:
%matplotlib qt5
fig, ax = plot_ccurve(ccurves[0], label=f'I={intensities[0]*1000:.2f}', area=a_an)

for ccurve, intsy in zip(ccurves[1:], intensities[1:]):
    plot_ccurve_line(ax, ccurve, label=f'I={intsy*1000:.2f}', area=a_an)

ax.legend()
save_fig(fig, 'B/all.pdf')
fig.show()

In [168]:
intensities

array([0.04347826, 0.05279503, 0.06521739, 0.08074534, 0.09937888])

In [50]:
plt.clf()
plt.errorbar(*np.array([[intsy*1000, params['j_c']] \
                    for intsy, params in ccurve_specs]).T, xerr=d_intensites*1000, marker='*', yerr=0.000005/a_an)
plt.xlabel('Intensitaet [$mW/cm^2$]')
plt.ylabel('$j_{SC}$ [$A/cm^2$]')
plt.grid(which='both')
plt.savefig('./figs/B/j_sc.pdf', dpi=300)
#plt.xscale('log')
#plt.yscale('log')


In [51]:
plt.clf()
plt.errorbar(*np.array([[(intsy*1000), params['u_cc']] \
                    for intsy, params in ccurve_specs]).T, xerr=d_intensites*1000, yerr=0.001, marker='*')
plt.xlabel('Intensitaet [$mW/cm^2$]')
plt.ylabel('$V_{OC}$ [$V$]')
plt.xscale('log')
plt.grid(which='both')
plt.savefig('./figs/B/u_cc.pdf', dpi=300)
#plt.yscale('log')


In [103]:
0.011 * (.032/.011)**(2/5)

0.0168614765323676

In [105]:
ccurve_specs

[(0.034161490683229816,
  {'j_c': 0.0025912392307692305,
   'u_cc': 0.5086008577882963,
   'u_mlp': 0.3977111360504424,
   'p_mlp': 0.022268705563519103,
   'ff': 0.6498857684076272,
   'eta': 0.025071759410675354}),
 (0.052795031055900624,
  {'j_c': 0.01341955,
   'u_cc': 0.5600084576663334,
   'u_mlp': 0.37999930322896436,
   'p_mlp': 0.11432399757691399,
   'ff': 0.585101909146971,
   'eta': 0.08328580818951652}),
 (0.06521739130434784,
  {'j_c': 0.016769280769230767,
   'u_cc': 0.5613136094311547,
   'u_mlp': 0.36000019842026715,
   'p_mlp': 0.13293315750161686,
   'ff': 0.5431752390708393,
   'eta': 0.07839647750095351}),
 (0.08074534161490683,
  {'j_c': 0.02099583076923077,
   'u_cc': 0.5641834857878043,
   'u_mlp': 0.3399999063957519,
   'p_mlp': 0.1534276805047185,
   'ff': 0.4981692745272282,
   'eta': 0.07308241586171502}),
 (0.09937888198757765,
  {'j_c': 0.025274496153846155,
   'u_cc': 0.5675239554252917,
   'u_mlp': 0.32765580118957827,
   'p_mlp': 0.17174272136274898,
  

In [161]:
plt.clf()
points = np.arange(0,6)
ints = .011 * (.032/.011)**(points/5)
plt.plot(np.arange(1,6), intensities, ints)

In [162]:
intensities

array([0.03416149, 0.05279503, 0.06521739, 0.08074534, 0.09937888])

In [163]:
ints

array([0.011     , 0.01361897, 0.01686148, 0.02087599, 0.02584631,
       0.032     ])